### ISSUE TITLE
ClaimFormTester Fonet

### ISSUE THREAD

**Issue by michaelachrisco** [bvanfleet/X12.NET#9]
**Describe the bug**
I am attempting to run some of the tests and do some basic testing on the 834 and came across this error:
ClaimFormTester: The name 'Fonet' does not exist in the current context	
X12Parser-1\tests\OopFactory.X12.Hipaa.Tests.Unit\Claims\ClaimFormTester.cs	69	Active
Running on Visual Studio 

**To Reproduce**
1. Right click on ClaimFormTester unit test and select Run Unit Tests

**Expected behavior**
I expect the unit test to not fail.

**Desktop (please complete the following information):**
 - OS: Name	Microsoft Windows 10 Pro
 - Version 10.0.17134 Build 17134

**Comment by bvanfleet** [comment]
Thanks for the catch. Strange... when I had removed the old DLL and added the NuGet reference, it seemed to work fine then. However, I added the reference and pushed commit 57df05734a694190bd35504cbccb319734c8c346

I am aware of 9 test cases that fail on my machine, and am investigating them as part of bug #3
